version: '3.8'

services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: russian_proverbs
    ports:
      - "5432:5432"
    volumes:
      - ./db/create_table.sql:/docker-entrypoint-initdb.d/create_table.sql
      - ./db/insert_data.sql:/docker-entrypoint-initdb.d/insert_data.sql
      - db_data:/var/lib/postgresql/data_new
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d russian_proverbs" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

#  app:
#    build: .
#    ports:
#      - "3000:3000"
#    depends_on:
#      - db
#    environment:
#      DATABASE_HOST: db
#      DATABASE_PORT: 5432
#      DATABASE_USERNAME: admin
#      DATABASE_PASSWORD: password
#      DATABASE_NAME: russian_proverbs
#      DATABASE_DIALECT: postgres

volumes:
  db_data: