INSERT INTO Proverb (Russian_Proverb, English_Translation, Meaning_Explanation, Category)
VALUES
    ('Без труда не вытащишь и рыбку из пруда.', 'You can''t pull a fish out of a pond without effort.', 'You have to work hard to achieve something.', 'Work'),
    ('Век живи - век учись.', 'Live and learn.', 'You never stop learning.', 'Education'),
    ('Глаза боятся, а руки делают.', 'The eyes are afraid, but the hands do.', 'You should not let yourself be discouraged by your fears.', 'Courage'),
    ('Голод не тётка.', 'Hunger is no aunt.', 'Hunger is a strong drive.', 'Hunger'),
    ('Гусь свинье не товарищ.', 'A goose is not a comrade to a pig.', 'People with different backgrounds do not fit together.', 'Differences'),
    ('Делу время, потехе час.', 'Time for work, an hour for fun.', 'You should not only work but also have fun.', 'Work and Leisure'),
    ('Доверяй, но проверяй.', 'Trust, but verify.', 'You should not blindly trust but also verify.', 'Trust'),
    ('Дорога ложка к обеду.', 'A spoon is good for lunch.', 'Everything has its time.', 'Timing'),
    ('Друг познаётся в беде.', 'A friend in need is a friend indeed.', 'True friends show themselves in difficult times.', 'Friendship'),
    ('Дурак думкой богатеет.', 'A fool gets rich in his thoughts.', 'Daydreaming does not lead to success.', 'Daydreaming'),
    ('Есть хлеб, да нечем мазать.', 'There is bread, but nothing to spread.', 'There is enough, but it cannot be used.', 'Scarcity'),
    ('За двумя зайцами погонишься, ни одного не поймаешь.', 'If you chase two hares, you will catch none.', 'You should not take on too much at once.', 'Goals'),
    ('Земля слухом полнится.', 'The earth is full of rumors.', 'Rumors spread quickly.', 'Rumors'),
    ('И волки сыты, и овцы целы.', 'Both the wolves are fed and the sheep are safe.', 'A solution that satisfies everyone.', 'Solution'),
    ('И рыбку съесть, и косточкой не подавиться.', 'To eat the fish and not choke on the bones.', 'To make the best of a situation without any disadvantages.', 'Advantages'),
    ('Капля камень точит.', 'A drop wears away a stone.', 'Perseverance leads to success.', 'Perseverance'),
    ('Клин клином вышибают.', 'A wedge is driven out by a wedge.', 'You fight something with the same means.', 'Conflict'),
    ('Копейка рубль бережёт.', 'A penny saves a ruble.', 'Small amounts add up to a large sum.', 'Thrift'),
    ('Красна птица перьем, а человек уменьем.', 'A bird is beautiful with its feathers, and a man with his skills.', 'Everyone is beautiful in their own way.', 'Beauty'),
    ('Кто не работает, тот не ест.', 'He who does not work, does not eat.', 'Only those who work earn their living.', 'Work'),
    ('Лучше поздно, чем никогда.', 'Better late than never.', 'It is never too late to do something.', 'Time'),
    ('Москва не сразу строилась.', 'Moscow was not built in a day.', 'Great things take time.', 'Time'),
    ('На вкус и цвет товарища нет.', 'There is no companion for taste and color.', 'Everyone has their own taste.', 'Taste'),
    ('Не всё золото, что блестит.', 'Not all that glitters is gold.', 'Not everything that glitters is valuable.', 'Value'),
    ('Не плюй в колодец, из которого пить придётся.', 'Don''t spit in the well you''ll have to drink from.', 'You should not harm something you may need in the future.', 'Caution'),
    ('Нет худа без добра.', 'There is no evil without good.', 'Everything has its good sides.', 'Positive Thinking'),
    ('Один в поле не воин.', 'One man is no warrior in the field.', 'You need help to achieve something.', 'Cooperation'),
    ('Око за око, зуб за зуб.', 'An eye for an eye, a tooth for a tooth.', 'Equal justice for all.', 'Justice'),
    ('Правда глаза колет.', 'The truth pricks the eyes.', 'The truth is often unpleasant.', 'Truth'),
    ('Работа не волк, в лес не убежит.', 'Work is not a wolf, it won''t run away into the forest.', 'You should not postpone work.', 'Work'),
    ('Семь раз отмерь, один раз отрежь.', 'Measure seven times, cut once.', 'You should take your time before doing something.', 'Planning'),
    ('Скажи мне, кто твой друг, и я скажу, кто ты.', 'Tell me who your friend is, and I will tell you who you are.', 'You are shaped by your friends.', 'Friendship'),
    ('Собака лает, ветер носит.', 'The dog barks, the wind carries it away.', 'You should not listen to rumors.', 'Rumors'),
    ('Старый друг лучше новых двух.', 'An old friend is better than two new ones.', 'True friendship is valuable.', 'Friendship'),
    ('Тише едешь, дальше будешь.', 'The quieter you go, the further you will get.', 'With patience, you achieve more.', 'Patience'),
    ('Утро вечера мудренее.', 'The morning is wiser than the evening.', 'You should sleep on a problem before making a decision.', 'Decision'),
    ('Хлеб да соль.', 'Bread and salt.', 'Hospitality.', 'Hospitality'),
    ('Цыплят по осени считают.', 'Chickens are counted in the autumn.', 'You should not triumph too early.', 'Success'),
    ('Что посеешь, то и пожнёшь.', 'What you sow, you shall reap.', 'You reap what you sow.', 'Consequences'),
    ('Язык до Киева доведёт.', 'Language will lead you to Kiev.', 'With communication, you achieve your goals.', 'Communication'),
    ('Баба с возу — кобыле легче.', 'A woman off the cart, the mare is lighter.', 'This proverb suggests that sometimes it is better to get rid of unnecessary burdens or people.', 'Relief'),
    ('Без царя в голове.', 'Without a tsar in the head.', 'This proverb describes someone who is foolish or thoughtless.', 'Foolishness'),
    ('Близок локоть, да не укусишь.', 'The elbow is near, but you can''t bite it.', 'This proverb means that something is close but unattainable.', 'Unattainability'),
    ('Бог не выдаст, свинья не съест.', 'God won''t give it away, the pig won''t eat it.', 'This proverb expresses hope that something bad won''t happen.', 'Hope'),
    ('Большому кораблю — большое плавание.', 'A big ship needs a big voyage.', 'This proverb suggests that great abilities require great opportunities.', 'Abilities'),
    ('Была бы шея, а хомут найдется.', 'If there were a neck, a collar would be found.', 'This proverb means that if there is a need, the means to fulfill it will be found.', 'Needs'),
    ('Век живи — век учись, дураком помрёшь.', 'Live a century, learn a century, you''ll die a fool.', 'This proverb emphasizes the importance of lifelong learning, even if you learn a lot, you can still feel like a fool sometimes.', 'Lifelong Learning'),
    ('Видит око, да зуб неймёт.', 'The eye sees, but the tooth can''t take it.', 'This proverb means that you can see something desirable, but you can''t have it.', 'Desire'),
    ('Взялся за гуж, не говори, что не дюж.', 'If you have taken hold of the rope, don''t say you are not strong enough.', 'This proverb encourages people to be responsible for their commitments.', 'Responsibility'),
    ('Вода камень точит.', 'Water wears away a stone.', 'This proverb emphasizes the power of perseverance and persistence.', 'Perseverance'),
    ('Волка ноги кормят.', 'The wolf is fed by his legs.', 'This proverb means that one has to work hard to survive.', 'Hard Work'),
    ('Всё хорошо, что хорошо кончается.', 'All is well that ends well.', 'This proverb suggests that the outcome of a situation is more important than the difficulties encountered along the way.', 'Outcome'),
    ('Где раки зимуют.', 'Where crayfish spend the winter.', 'This phrase is used to describe a place that is far away or difficult to find.', 'Remoteness'),
    ('Глаза — зеркало души.', 'Eyes are the mirror of the soul.', 'This proverb suggests that a person''s eyes can reveal their true feelings and thoughts.', 'Feelings'),
    ('Гол как сокол.', 'As bare as a falcon.', 'This phrase describes someone who is very poor.', 'Poverty'),
    ('Горе не беда, была бы шея.', 'Grief is not a trouble, if there were a neck.', 'This proverb means that as long as you are alive, you can overcome any difficulties.', 'Optimism'),
    ('Губа не дура.', 'The lip is not a fool.', 'This proverb is used to describe someone who has good taste or knows what they want.', 'Good Taste'),
    ('Дело мастера боится.', 'The work is afraid of the master.', 'This proverb means that a skilled person can easily handle any task.', 'Skill'),
    ('Деньги — зло, но без них никуда.', 'Money is evil, but you can''t do without it.', 'This proverb acknowledges the negative aspects of money, but also its necessity.', 'Money'),
    ('Дождь идёт не там, где ждут, а там, где жнут.', 'Rain falls not where they wait, but where they reap.', 'This proverb means that good things don''t always come to those who expect them, but to those who work hard.', 'Hard Work'),
    ('Дорого яичко к Христову дню.', 'An egg is expensive on Easter Day.', 'This proverb means that something is valuable when it is needed most.', 'Value'),
    ('Дурак и в церкви дурак.', 'A fool is a fool even in church.', 'This proverb means that foolishness cannot be hidden or disguised.', 'Foolishness'),
    ('Дыма без огня не бывает.', 'There is no smoke without fire.', 'This proverb means that there is always a reason for any event or rumor.', 'Cause and Effect'),
    ('Ешь, пока рот свеж.', 'Eat while your mouth is fresh.', 'This proverb encourages people to take advantage of opportunities while they last.', 'Opportunity'),
    ('Жизнь прожить — не поле перейти.', 'To live life is not like crossing a field.', 'This proverb emphasizes that life is a complex and challenging journey.', 'Life'),
    ('За битого два небитых дают.', 'For one beaten they give two unbeaten.', 'This proverb means that it is better to learn from others'' mistakes than to make your own.', 'Learning from Mistakes'),
    ('За двумя зайцами погонишься — ни одного не поймаешь.', 'If you chase two hares, you will catch none.', 'This proverb advises against trying to do too many things at once.', 'Goals'),
    ('Здоровье дороже золота.', 'Health is more precious than gold.', 'This proverb emphasizes the importance of health.', 'Health'),
    ('И конь о четырёх ногах, да спотыкается.', 'Even a horse with four legs stumbles.', 'This proverb means that everyone makes mistakes, even the most skilled or experienced people.', 'Mistakes'),
    ('История — учительница жизни.', 'History is the teacher of life.', 'This proverb emphasizes the importance of learning from the past.', 'History'),
    ('Как волка ни корми, он всё в лес глядит.', 'However you feed the wolf, he still looks to the forest.', 'This proverb means that people''s basic nature or desires will always prevail.', 'Human Nature'),
    ('Копейка рубль бережёт.', 'A penny saves a ruble.', 'This proverb emphasizes the importance of saving money, even small amounts.', 'Saving'),
    ('Кто рано встаёт, тому Бог подаёт.', 'God helps those who rise early.', 'This proverb encourages people to be diligent and hardworking.', 'Diligence'),
    ('Лучше синица в руке, чем журавль в небе.', 'A bird in the hand is better than a crane in the sky.', 'This proverb advises people to be content with what they have and not to chase after unrealistic goals.', 'Contentment'),
    ('Мал золотник, да дорог.', 'Small is the gold coin, but precious.', 'This proverb means that something small can be very valuable.', 'Value'),
    ('На нет и суда нет.', 'There is no trial for nothing.', 'This proverb means that there is no point in arguing about something that does not exist.', 'Pointlessness'),
    ('Не хлебом единым жив человек.', 'Man does not live by bread alone.', 'This proverb emphasizes the importance of spiritual and intellectual needs, not just material ones.', 'Values'),
    ('Обещанного три года ждут.', 'The promised is awaited for three years.', 'This proverb means that promises are often not kept.', 'Promises'),
    ('По одёжке встречают, по уму провожают.', 'They meet you by your clothes, but see you off by your mind.', 'This proverb suggests that first impressions are based on appearance, but that true value is judged by intelligence and character.', 'Impression'),
    ('Пьяному море по колено.', 'The sea is knee-deep to a drunkard.', 'This proverb describes a person who is overconfident due to intoxication.', 'Overconfidence'),
    ('Рыба ищет, где глубже, а человек, где лучше.', 'A fish seeks where it is deeper, and a man where it is better.', 'This proverb means that people are naturally inclined to seek better opportunities and living conditions.', 'Striving for Better'),
    ('Своя рубашка ближе к телу.', 'One''s own shirt is closer to the body.', 'This proverb means that people are naturally more concerned about their own interests than those of others.', 'Self-Interest'),
    ('Сила солому ломит.', 'Strength breaks straw.', 'This proverb means that might makes right.', 'Power'),
    ('Слово — не воробей, вылетит — не поймаешь.', 'A word is not a sparrow, once it flies out, you won''t catch it.', 'This proverb emphasizes the importance of being careful with one''s words.', 'Words'),
    ('Собака на сене лежит, сама не ест и другим не даёт.', 'The dog lies on the hay, doesn''t eat it himself and doesn''t give it to others.', 'This proverb describes a selfish person who prevents others from enjoying something they don''t need themselves.', 'Selfishness'),
    ('Ум хорошо, а два лучше.', 'One head is good, but two are better.', 'This proverb emphasizes the value of collaboration and teamwork.', 'Teamwork'),
    ('Век живи - век учись.', 'Live and learn.', 'This proverb emphasizes the importance of lifelong learning.', 'Education'),
    ('Не всё золото, что блестит.', 'Not all that glitters is gold.', 'This proverb warns against judging things by their appearance.', 'Value'),
    ('Москва не сразу строилась.', 'Moscow wasn''t built in a day.', 'This proverb emphasizes that great things take time and effort.', 'Time'),
    ('Тише едешь - дальше будешь.', 'The quieter you go, the further you will get.', 'This proverb emphasizes the importance of patience and persistence.', 'Patience'),
    ('Что посеешь, то и пожнёшь.', 'What you sow, you shall reap.', 'This proverb emphasizes the principle of cause and effect.', 'Consequences'),
    ('Лучше поздно, чем никогда.', 'Better late than never.', 'This proverb encourages perseverance and emphasizes that it''s never too late to do something.', 'Time'),
    ('Семь раз отмерь - один раз отрежь.', 'Measure seven times, cut once.', 'This proverb emphasizes the importance of careful planning and consideration before taking action.', 'Planning'),
    ('В гостях хорошо, а дома лучше.', 'It''s good to visit, but it''s better at home.', 'This proverb emphasizes the importance of home and family.', 'Home'),
    ('Язык до Киева доведёт.', 'Language will lead you to Kiev.', 'This proverb emphasizes the importance of communication.', 'Communication'),
    ('Не имей сто рублей, а имей сто друзей.', 'Don''t have a hundred rubles, but have a hundred friends.', 'This proverb emphasizes the importance of friendship.', 'Friendship'),
    ('Утро вечера мудренее.', 'The morning is wiser than the evening.', 'This proverb suggests that it''s best to sleep on a problem before making a decision.', 'Decision'),
    ('Работа не волк - в лес не убежит.', 'Work is not a wolf, it won''t run away into the forest.', 'This proverb is used to encourage someone to get back to work.', 'Work'),
    ('Глаза боятся, а руки делают.', 'The eyes are afraid, but the hands do.', 'This proverb emphasizes the importance of taking action despite fear or doubt.', 'Action'),
    ('Не всё коту масленица.', 'Not every day is a holiday for a cat.', 'This proverb means that life is not always easy or fun.', 'Life'),
    ('Без труда не вытащишь и рыбку из пруда.', 'You can''t pull a fish out of a pond without effort.', 'This highlights the importance of hard work and effort in achieving one''s goals.', 'Work'),
    ('Не плюй в колодец, из которого пить придётся.', 'Don''t spit in the well you''ll have to drink from.', 'This proverb warns against doing harm to something or someone that you may need in the future.', 'Caution'),
    ('Слово не воробей - вылетит - не поймаешь.', 'A word is not a sparrow, once it flies out, you can''t catch it.', 'This proverb emphasizes the importance of being careful with your words.', 'Words'),
    ('В чужой монастырь со своим уставом не ходят.', 'Don''t go to a foreign monastery with your own rules.', 'This proverb advises against imposing your own customs or beliefs on others when you are in their territory.', 'Culture'),
    ('Лучше синица в руке, чем журавль в небе.', 'A bird in the hand is better than a crane in the sky.', 'This proverb emphasizes the importance of being content with what you have rather than chasing after something uncertain or unattainable.', 'Contentment'),
    ('Волков бояться - в лес не ходить.', 'If you''re afraid of wolves, don''t go into the forest.', 'This proverb suggests that if you let fear hold you back, you will miss out on opportunities and experiences.', 'Fear'),
    ('Сколько верёвочке ни виться - кончику быть.', 'No matter how long the rope twists, it will eventually have an end.', 'This proverb means that everything has an end, and that even difficult times will eventually pass.', 'End'),
    ('С миру по нитке - голому рубашка.', 'From the world a thread - a shirt for a naked man.', 'This proverb emphasizes the power of collective effort.', 'Community'),
    ('Не хлебом единым жив человек.', 'Man does not live by bread alone.', 'This proverb emphasizes the importance of spiritual and emotional needs in addition to material ones.', 'Values'),
    ('Всё хорошо, что хорошо кончается.', 'All is well that ends well.', 'This proverb suggests that the outcome of a situation is more important than the difficulties encountered along the way.', 'Outcome'),
    ('Как аукнется, так и откликнется.', 'As you call, so shall you be answered.', 'This proverb emphasizes the principle of reciprocity.', 'Reciprocity'),
    ('Под лежачий камень вода не течёт.', 'Water doesn''t flow under a lying stone.', 'This proverb emphasizes the importance of taking action and being proactive.', 'Action'),
    ('В тихом омуте черти водятся.', 'Devils are found in still waters.', 'This proverb warns against judging people or situations by their outward appearance.', 'Appearance'),
    ('Не ошибается тот, кто ничего не делает.', 'He who does nothing makes no mistakes.', 'This proverb suggests that everyone makes mistakes, and that it is important to learn from them.', 'Mistakes'),
    ('Ученье - свет, а неученье - тьма.', 'Learning is light, and ignorance is darkness.', 'This proverb emphasizes the importance of education and knowledge.', 'Education'),
    ('Одна голова хорошо, а две лучше.', 'One head is good, but two are better.', 'This proverb emphasizes the value of collaboration and teamwork.', 'Teamwork'),
    ('Правда глаза колет.', 'The truth pricks the eyes.', 'This proverb suggests that the truth can be painful to hear or accept.', 'Truth'),
    ('Не откладывай на завтра то, что можно сделать сегодня.', 'Don''t put off until tomorrow what you can do today.', 'This proverb emphasizes the importance of being punctual and not procrastinating.', 'Procrastination'),
    ('Встречают по одёжке, а провожают по уму.', 'They meet you by your clothes, but see you off by your mind.', 'This proverb suggests that first impressions are often based on appearance, but that true value is judged by intelligence and character.', 'Impression'),
    ('Баба с возу - кобыле легче.', 'A woman off the cart, the mare is lighter.', 'This proverb suggests that sometimes it is better to get rid of unnecessary burdens or people.', 'Relief'),
    ('Без царя в голове.', 'Without a tsar in the head.', 'This proverb describes someone who is foolish or thoughtless.', 'Foolishness'),
    ('Близок локоть, да не укусишь.', 'The elbow is near, but you can''t bite it.', 'This proverb means that something is close but unattainable.', 'Unattainability'),
    ('Бог не выдаст - свинья не съест.', 'God won''t give it away, the pig won''t eat it.', 'This proverb expresses hope that something bad won''t happen.', 'Hope'),
    ('Большому кораблю - большое плавание.', 'A big ship needs a big voyage.', 'This proverb suggests that great abilities require great opportunities.', 'Abilities'),
    ('Была бы шея, а хомут найдется.', 'If there were a neck, a collar would be found.', 'This proverb means that if there is a need, the means to fulfill it will be found.', 'Needs'),
    ('Видит око, да зуб неймёт.', 'The eye sees, but the tooth can''t take it.', 'This proverb means that you can see something desirable, but you can''t have it.', 'Desire'),
    ('Взялся за гуж - не говори, что не дюж.', 'If you have taken hold of the rope, don''t say you are not strong enough.', 'This proverb encourages people to be responsible for their commitments.', 'Responsibility'),
    ('Вода камень точит.', 'Water wears away a stone.', 'This proverb emphasizes the power of perseverance and persistence.', 'Perseverance'),
    ('Волка ноги кормят.', 'The wolf is fed by his legs.', 'This proverb means that one has to work hard to survive.', 'Hard Work'),
    ('Где раки зимуют.', 'Where crayfish spend the winter.', 'This phrase is used to describe a place that is far away or difficult to find.', 'Remoteness'),
    ('Лучше один раз увидеть, чем сто раз услышать.', 'Better to see once than to hear a hundred times.', 'This proverb emphasizes the importance of firsthand experience.', 'Experience'),
    ('Не ошибается тот, кто ничего не делает.', 'He who does nothing makes no mistakes.', 'This proverb suggests that everyone makes mistakes, and that it is important to learn from them.', 'Mistakes'),
    ('Ученье - свет, а неученье - тьма.', 'Learning is light, and ignorance is darkness.', 'This proverb emphasizes the importance of education and knowledge.', 'Education'),
    ('Одна голова хорошо, а две лучше.', 'One head is good, but two are better.', 'This proverb emphasizes the value of collaboration and teamwork.', 'Teamwork'),
    ('Правда глаза колет.', 'The truth pricks the eyes.', 'This proverb suggests that the truth can be painful to hear or accept.', 'Truth'),
    ('Не откладывай на завтра то, что можно сделать сегодня.', 'Don''t put off until tomorrow what you can do today.', 'This proverb emphasizes the importance of being punctual and not procrastinating.', 'Procrastination'),
    ('Встречают по одёжке, а провожают по уму.', 'They meet you by your clothes, but see you off by your mind.', 'This proverb suggests that first impressions are often based on appearance, but that true value is judged by intelligence and character.', 'Impression'),
    ('Баба с возу - кобыле легче.', 'A woman off the cart, the mare is lighter.', 'This proverb suggests that sometimes it is better to get rid of unnecessary burdens or people.', 'Relief'),
    ('Без царя в голове.', 'Without a tsar in the head.', 'This proverb describes someone who is foolish or thoughtless.', 'Foolishness'),
    ('Близок локоть, да не укусишь.', 'The elbow is near, but you can''t bite it.', 'This proverb means that something is close but unattainable.', 'Unattainability'),
    ('Бог не выдаст - свинья не съест.', 'God won''t give it away, the pig won''t eat it.', 'This proverb expresses hope that something bad won''t happen.', 'Hope'),
    ('Большому кораблю - большое плавание.', 'A big ship needs a big voyage.', 'This proverb suggests that great abilities require great opportunities.', 'Abilities'),
    ('Была бы шея, а хомут найдется.', 'If there were a neck, a collar would be found.', 'This proverb means that if there is a need, the means to fulfill it will be found.', 'Needs'),
    ('Видит око, да зуб неймёт.', 'The eye sees, but the tooth can''t take it.', 'This proverb means that you can see something desirable, but you can''t have it.', 'Desire'),
    ('Взялся за гуж - не говори, что не дюж.', 'If you have taken hold of the rope, don''t say you are not strong enough.', 'This proverb encourages people to be responsible for their commitments.', 'Responsibility'),
    ('Вода камень точит.', 'Water wears away a stone.', 'This proverb emphasizes the power of perseverance and persistence.', 'Perseverance'),
    ('Волка ноги кормят.', 'The wolf is fed by his legs.', 'This proverb means that one has to work hard to survive.', 'Hard Work'),
    ('Где раки зимуют.', 'Where crayfish spend the winter.', 'This phrase is used to describe a place that is far away or difficult to find.', 'Remoteness'),
    ('Глаза - зеркало души.', 'Eyes are the mirror of the soul.', 'This proverb suggests that a person''s eyes can reveal their true feelings and thoughts.', 'Feelings'),
    ('Гол как сокол.', 'As bare as a falcon.', 'This phrase describes someone who is very poor.', 'Poverty'),
    ('Горе не беда, была бы шея.', 'Grief is not a trouble, if there were a neck.', 'This proverb means that as long as you are alive, you can overcome any difficulties.', 'Optimism'),
    ('Дело мастера боится.', 'The work is afraid of the master.', 'This proverb means that a skilled person can easily handle any task. It emphasizes the importance of mastery and expertise.', 'Skill'),
    ('Деньги — зло, но без них никуда.', 'Money is evil, but you can''t do without it.', 'This proverb acknowledges the negative aspects of money, but also its necessity in modern life. It highlights the complex relationship people have with money.', 'Money'),
    ('Дождь идёт не там, где ждут, а там, где жнут.', 'Rain falls not where they wait, but where they reap.', 'This proverb means that good things don''t always come to those who expect them, but to those who work hard. It emphasizes the importance of action and effort.', 'Effort'),
    ('Дорого яичко к Христову дню.', 'An egg is expensive on Easter Day.', 'This proverb means that something is valuable when it is needed most. It highlights the concept of supply and demand and the fluctuation of value depending on context.', 'Value'),
    ('Дурак и в церкви дурак.', 'A fool is a fool even in church.', 'This proverb means that foolishness cannot be hidden or disguised. It suggests that a person''s true nature will always be revealed, regardless of the setting.', 'Foolishness'),
    ('Дыма без огня не бывает.', 'There is no smoke without fire.', 'This proverb means that there is always a reason for any event or rumor. It emphasizes the importance of looking for the underlying cause of things.', 'Cause and Effect'),
    ('Ешь, пока рот свеж.', 'Eat while your mouth is fresh.', 'This proverb encourages people to take advantage of opportunities while they last. It emphasizes the fleeting nature of opportunities and the importance of seizing the moment.', 'Opportunity'),
    ('Жизнь прожить — не поле перейти.', 'To live life is not like crossing a field.', 'This proverb emphasizes that life is a complex and challenging journey. It suggests that life is full of obstacles and requires effort and resilience to navigate.', 'Life'),
    ('За битого два небитых дают.', 'For one beaten they give two unbeaten.', 'This proverb means that it is better to learn from others'' mistakes than to make your own. It highlights the value of experience and the importance of learning from the past.', 'Learning from Mistakes'),
    ('За двумя зайцами погонишься — ни одного не поймаешь.', 'If you chase two hares, you will catch none.', 'This proverb advises against trying to do too many things at once. It emphasizes the importance of focus and prioritization.', 'Focus'),
    ('Здоровье дороже золота.', 'Health is more precious than gold.', 'This proverb emphasizes the importance of health. It suggests that health is the most valuable thing a person can have.', 'Health'),
    ('И конь о четырёх ногах, да спотыкается.', 'Even a horse with four legs stumbles.', 'This proverb means that everyone makes mistakes, even the most skilled or experienced people. It emphasizes the human nature of error.', 'Mistakes'),
    ('История — учительница жизни.', 'History is the teacher of life.', 'This proverb emphasizes the importance of learning from the past. It suggests that studying history can help us avoid repeating past mistakes.', 'History'),
    ('Как волка ни корми, он всё в лес глядит.', 'However you feed the wolf, he still looks to the forest.', 'This proverb means that people''s basic nature or desires will always prevail. It highlights the idea that people are inherently driven by their instincts.', 'Human Nature'),
    ('Копейка рубль бережёт.', 'A penny saves a ruble.', 'This proverb emphasizes the importance of saving money, even small amounts. It suggests that small savings can add up to a significant sum over time.', 'Saving'),
    ('Кто рано встаёт, тому Бог подаёт.', 'God helps those who rise early.', 'This proverb encourages people to be diligent and hardworking. It suggests that those who are proactive and industrious are more likely to succeed.', 'Diligence'),
    ('Лучше синица в руке, чем журавль в небе.', 'A bird in the hand is better than a crane in the sky.', 'This proverb advises people to be content with what they have and not to chase after unrealistic goals. It emphasizes the value of appreciating the present rather than longing for something uncertain.', 'Contentment'),
    ('Мал золотник, да дорог.', 'Small is the gold coin, but precious.', 'This proverb means that something small can be very valuable. It highlights the idea that value is not always determined by size or quantity.', 'Value'),
    ('На нет и суда нет.', 'There is no trial for nothing.', 'This proverb means that there is no point in arguing about something that does not exist. It suggests that it is futile to debate the nonexistent.', 'Futility'),
    ('Не хлебом единым жив человек.', 'Man does not live by bread alone.', 'This proverb emphasizes the importance of spiritual and intellectual needs, not just material ones. It suggests that human well-being depends on more than just physical sustenance.', 'Values');